name: Molecule Testing 

on: [push]

jobs:
  build:
    # Job name
    name: Install Molecule
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # This step installs Molecule using Pip
      - name: Install
        run: sudo -H pip install molecule
      # This step tests Molecule after installing
      - name: Test
        run: ls -ltrh
