name: Molecule Testing 

on: [push]

jobs:
  build:
    # Job name
    name: Install Molecule
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step installs Molecule using Pip
      - name: Install
        run: pip install --user molecule
      # This step prints an output (time) from the previous step's action.
      - name: Test 
        run: molecule check
